# Paths are relative to config file location
relative-paths: yes

# performance settings
beam-size: 12
devices: [0]
normalize: yes
cpu-threads: 2
gpu-threads: 0

# scorer configuration
scorers:
  F0:
    path: ../../build/model.en-ru.npz
    type: Nematus
bpe: ../data/enru/enru.bpe

# scorer weights
weights:
  F0: 1.0

# vocabularies
source-vocab: ../data/enru/vocab.en.json
target-vocab: ../data/enru/vocab.ru.json
